minimal cleaning + building baskets (transactions)
exports prior baskets + train baskets kept products list maybe

In [2]:
#import library
from pathlib import Path
import pandas as pd

In [3]:
#load data csv that will be use to create basket
orders=pd.read_csv("../data/orders.csv")
products=pd.read_csv("../data/products.csv")
order_products__prior=pd.read_csv("../data/order_products__prior.csv")
order_products__train=pd.read_csv("../data/order_products__train.csv")

In [5]:
#Filtrage to having TOP N more frequents products in prior to avoid product rarely command. Choosing 3000 here

TOP_N_PRODUCTS = 3000  # first try, more or less after result

# putting the filter on  prior an train order for no error in the evaluation

top_products = order_products__prior["product_id"].value_counts().head(TOP_N_PRODUCTS).index

prior_small = order_products__prior[order_products__prior["product_id"].isin(top_products)].copy()
train_small = order_products__train[order_products__train["product_id"].isin(top_products)].copy()

print("prior_small:", prior_small.shape)
print("train_small:", train_small.shape)

prior_small: (23716660, 4)
train_small: (984663, 4)

In [6]:
#creation of basket by transform order_id in list of product_id
def build_baskets(df):
    baskets = (
        df.groupby("order_id")["product_id"]
        .apply(lambda s: sorted(set(s.tolist())))
        .reset_index()
        .rename(columns={"product_id": "basket"})
    )
    return baskets

prior_baskets = build_baskets(prior_small)
train_baskets = build_baskets(train_small)

display(prior_baskets.head())
display(train_baskets.head())

print("nb prior baskets:", len(prior_baskets))
print("nb train baskets:", len(train_baskets))

   order_id                                             basket
0         2                  [1819, 9327, 17794, 28985, 33120]
1         3  [17461, 17668, 17704, 21903, 24838, 32665, 337...
2         4  [17616, 21351, 25146, 27761, 34862, 39758, 402...
3         5  [6184, 6348, 8479, 12962, 13176, 13245, 23909,...
4         7                                     [34050, 46802]

   order_id                                             basket
0         1         [10246, 11109, 13176, 22035, 47209, 49683]
1        36         [19660, 34497, 43086, 46979, 48679, 49235]
2        38  [4461, 11913, 18159, 21616, 23622, 28842, 3243...
3        96         [20574, 24489, 27966, 30391, 39275, 40706]
4        98  [329, 790, 1939, 3880, 4357, 7461, 8859, 13176...

nb prior baskets: 3115534
nb train baskets: 126408

In [ ]:
#Save the tables create in csv for the model utilisation in a outputs folder

prior_baskets.to_csv("../outputs/prior_baskets.csv", index=False)
train_baskets.to_csv("../outputs/train_baskets.csv", index=False)

products_small = products[products["product_id"].isin(top_products)].copy()
products_small.to_csv("../outputs/products_small.csv", index=False)

print("Saved to: ../outputs")

Saved to: ../outputs